FROM apache/airflow:2.10.5-python3.11

COPY requirements-airflow.txt /requirements-airflow.txt
RUN pip install --no-cache-dir -r /requirements-airflow.txt

COPY --chown=airflow:root dags /opt/airflow/dags
COPY --chown=airflow:root src /opt/airflow/retailflow/src
COPY --chown=airflow:root sql /opt/airflow/retailflow/sql
COPY --chown=airflow:root data/raw /opt/airflow/retailflow/data/raw
